services:
  app:
    build: .
    ports:
      - 127.0.0.1:9000:8000
      - 127.0.0.1:5678:5678
    volumes:
      - .:/code
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    depends_on:
      - ollama
      - ollama-webui
    networks:
      - ollama-docker
      
  ollama:
    volumes:
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:0.6.2
    ports:
      - 127.0.0.1:7870:11434
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - HF_ENDPOINT=https://hf-mirror.com
    networks:
      - ollama-docker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:0.6.2
    container_name: ollama-webui
    volumes:
      - ./ollama/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 127.0.0.1:8080:8080
    environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
      - OLLAMA_BASE_URLS=http://host.docker.internal:7870 #comma separated ollama hosts
      - ENV=dev
      - WEBUI_AUTH=True
      - WEBUI_NAME=CUC AI
      - WEBUI_URL=http://cuc.ai:8080
      - WEBUI_SECRET_KEY=t0p-s3cr3t
      - HF_ENDPOINT=https://hf-mirror.com
    restart: unless-stopped
    networks:
      - ollama-docker

  one-api:
    image: "justsong/one-api:v0.6.10"
    container_name: one-api
    restart: always
    command: --log-dir /app/logs
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./oneapi/data:/data
      - ./oneapi/logs:/app/logs
    environment:
      - SQL_DSN=oneapi:123456@tcp(db:3306)/one-api  # 修改此行，或注释掉以使用 SQLite 作为数据库
      - REDIS_CONN_STRING=redis://redis
      - SESSION_SECRET=random_string12380sdjfleafasgf1-3lajflaksdf  # 修改为随机字符串
      - TZ=Asia/Shanghai
#      - NODE_TYPE=slave  # 多机部署时从节点取消注释该行
#      - SYNC_FREQUENCY=60  # 需要定期从数据库加载数据时取消注释该行
#      - FRONTEND_BASE_URL=https://openai.justsong.cn  # 多机部署时从节点取消注释该行
    depends_on:
      - redis
      - db
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $2}'" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - ollama-docker

  redis:
    image: "redis:7.4.2"
    container_name: redis
    restart: always
    networks:
      - ollama-docker

  db:
    image: "mysql:8.2.0"
    restart: always
    container_name: mysql
    volumes:
      - ./oneapi/mysql:/var/lib/mysql  # 挂载目录，持久化存储
    ports:
      - '127.0.0.1:3306:3306'
    environment:
      TZ: Asia/Shanghai   # 设置时区
      MYSQL_ROOT_PASSWORD: 'zhe5shiw0MIMA' # 设置 root 用户的密码
      MYSQL_USER: oneapi   # 创建专用用户
      MYSQL_PASSWORD: '123456'    # 设置专用用户密码
      MYSQL_DATABASE: one-api   # 自动创建数据库
    networks:
      - ollama-docker

networks:
  ollama-docker:
    external: false
